### ISSUE TITLE
windows issue

### ISSUE THREAD

**Issue by CarolineMorton** [ebmdatalab/custom-docker#1]
Hi 

I have got docker working on my computer all ok. Can spin up containers, install requirements, use jupyter notebook and save them. 

I have tried with Helen on her windows machine today and running into issues. The issue is the same as this one:--> https://github.com/docker/for-win/issues/868

We are able to install Docker but when you log in, you get an error message. 
![image](https://user-images.githubusercontent.com/25401512/66406538-b0870f00-e9e3-11e9-9d61-ced835e853d5.png)

We have worked through the solution mentioned in the git issue and manually added her to the docker-user group (see https://forums.docker.com/t/docker-for-windows-access-denied-beta/33061) but whenever Helen logs out and in again as recommended when prompted, her details are then deleted from the docker-user group. 

Anyone have any ideas?

**Comment by CarolineMorton** [comment]
I should mention that this step is completely not required on a mac ... just another reason macs rule!

**Comment by sebbacon** [comment]
No bright ideas here I'm afraid - apart from I can't believe this is an unsolved problem since 2017?!

**Comment by sebbacon** [comment]
I wonder if this is only with uni laptops (i.e. only when you're logging into a network domain)

**Comment by sebbacon** [comment]
@CarolineMorton we've just been chatting about this and we think we need a Windows expert. The challenge is to find a friendly tech person who is responsible for the ActiveDirectory domain. We may need Hilary's help to find out who this might be.

**Comment by sebbacon** [comment]
Things to try:
https://github.com/docker/for-win/issues/785#issuecomment-344805180
https://github.com/docker/for-win/issues/785#issuecomment-327237998

**Comment by CarolineMorton** [comment]
Ok, i will try on Friday. Agree about the Windows expert. 
I think the uni laptop thing may be a factor ... may try to borrow a windows laptop off someone
