### ISSUE TITLE
Unexpected capture of stdout in tests

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/custom-docker#10]
The `nbval` which we use in testing captures `stdout` (similar to `pytest`, but apparently with a different mechanism), and compares it with the recorded output in each cell.

In @alexwalkercebm's change detection package, [`R` packages are installed via `ryp2`](https://github.com/ebmdatalab/change_detection/blob/0e61a4bf6568848bf72fc35650752068bf4c8ee4/change_detection/functions.py#L16-L27) - without inspecting the code, I can see that this spawns subprocesses or threads that include make, gcc, R and three shells:

```
ggnome-terminal-(16267)─┬
                       ├─bash(14467)───su(19910)───bash(19912)───python(22309)───sh(22470)───sh(22471)───R(22475)───sh(22481)───make(22482)───gcc(22483)───cc1(22484)

```

The issue is that when you run a notebook via `jupyter notebook` and execute it from the browser interface, the `stdout` of the `gcc` process is captured by the `jupyter notebook` process, while the `stderr` of the `R` process is captured in the notebook cell.

Which in itself would be fine, but when you run `python -m pytest --nbval <notebook>`, all of the output is captured and stored as `stdout`, leading to an assertion failure.

**Comment by sebbacon** [comment]
I don't know if it's my cold, or just that it's all very fiddly, but I have lost interest in trying to work out the finer details of how `nbconvert` (used by `nbval` in this case, I think) differs from `jupyter notebook` in how it captures stdout.

Instead, I propose using the magic comment `NBVAL_IGNORE_OUTPUT` as a workaround wherever we import `change_detection.functions`:

```python
# NBVAL_IGNORE_OUTPUT

from change_detection import functions as chg
```

(Which unfortunately means remembering to do this every time we use it.  Maybe add a note to the README for the package itself?)

**Comment by alexwalkerepi** [comment]
The tests are now passing following this commit, but I had to add it to the cell containing `opioids_class.run()` too because that has a similar issue due to the `print` statement here:
https://github.com/ebmdatalab/change_detection/blob/0e61a4bf6568848bf72fc35650752068bf4c8ee4/change_detection/functions.py#L135
