### ISSUE TITLE
Make running on multiple ports easier

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/custom-docker#15]
Many researchers want to have multiple repos running. The current shell/batch scripts always launch on port 8888

It would be nice for them to automatically find the next available port; or if this is too fiddly, at least to prompt about which port to use.

**Comment by sebbacon** [comment]
Workaround:

The following line includes a bit that says `-p 8888:8888`

This tells docker to make port 8888 *in the linux container* appear on port 8888 *to your computer*

Change this to `-p 8889:8888` and it will appear on port 8889 *on your computer*.

This then allows you to have more than one notebook running at the same time.

https://github.com/ebmdatalab/custom-docker/blob/06c390c0e169d68e6367e308c12421130f513c82/run.bat#L4

**Comment by CarolineMorton** [comment]
I just tried to run 2 Docker containers with Jupyter projects on my mac, and it changed the second port to 8889 automatically; which is nice! This may be mac being helpful.

**Comment by sebbacon** [comment]
Doing this in batch script is a nightmare, so I perhaps I'll do it in Python and use something like [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html) to distribute it.
