### ISSUE TITLE
Badge status in README refers to custom-docker repo

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/custom-docker#22]
In `![status](https://github.com/ebmdatalab/custom-docker/workflows/Notebook%20checks/badge.svg)`, `custom-docker` should be replaced with the name of the repo.

**Comment by CarolineMorton** [comment]
Presumably we can't automate this... we could just change the readme to be clearer? I can do this unless there is a fancy way of automating? @sebbacon

**Comment by sebbacon** [comment]
We could change the `custom-docker` bit to say something like `<your-repo-name-here>` or whatever, so that at least the gif is broken by default, which means it's not misleading if nothing is done...?

**Comment by CarolineMorton** [comment]
Yes that works, and add a line in the developer.MD?

**Comment by inglesp** [comment]
Ah right -- for some reason (probably the word "template") I'd thought you could substitute the repo name into various places in the new repo.
