### ISSUE TITLE
No outputs displayed in run.exe cmd window

### ISSUE THREAD

**Issue by alexwalkerepi** [ebmdatalab/custom-docker#31]
The cmd window that `run.bat` opened would display the output from `stdout` and `stderr`. This is handy for seeing progress when running `change_detection`, but `run.exe` doesn't show any of that.

**Comment by sebbacon** [comment]
Can you test [this new run.exe](https://github.com/ebmdatalab/custom-docker/blob/better-port-mapping/run.exe)?

**Comment by alexwalkerepi** [comment]
Yes this works.
![image](https://user-images.githubusercontent.com/24895935/75164545-de61bb80-5718-11ea-8505-c23ea095bd8c.png)
