### ISSUE TITLE
mybinder progress writeup

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/custom-docker#9]
It would be nice to be able to launch our notebooks in mybinder.

This uses the following components:

* `repo2docker` to build a docker container based on a specified configuration format 
* `binder` to serve arbitrary containers, using:
  * `kubernetes` to manage multiple containers
  * `helm` to orchestrate their configuration
  * a proxy server to route requests for different repos to separate docker containers which are internally running on different ports

I have tried (and failed) to make our Dockerfile compatible with binder per [these notes](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html) (my attempts are [here](https://github.com/ebmdatalab/cusum-for-opioids-notebook/compare/mybinder-config?expand=1)).  I got as far as images correctly building, but the proxy server getting into a redirect loop, perhaps related to authentication tokens. The problem was it was almost impossible to debug, thanks to the complex interactions between the tornado proxy client, kubernetes pods, helm configurations, and the minikube (virtualbox-based) development environment [suggested in the documentation](https://github.com/jupyterhub/binderhub/blob/master/CONTRIBUTING.md).

**Comment by sebbacon** [comment]
I do think it's worth investigating using `repo2docker` for configuration rather than the current setup, though.

**Comment by sebbacon** [comment]
One immediate blocker I see: [no way of specifying PPAs](https://github.com/jupyter/repo2docker/issues/402), which we need to support `R` version 3.6

**Comment by sebbacon** [comment]
So, for now, the status quo seems fine.  Perhaps we can make our own configuration format to hide all the complexity of specifying an environment at some point.

**Comment by sebbacon** [comment]
For future reference, I think the easiest thing would be [Google Cloud Run](https://cloud.google.com/run/docs/quickstarts/build-and-deploy)

**Comment by CarolineMorton** [comment]
I've been poking through the Alan Turing Institute guide on Binder (and Jupyter). [This](https://github.com/alan-turing-institute/binderhub-deploy-gke) looks quite interesting. Will do some more reading.

**Comment by sebbacon** [comment]
Looks like it's still Binder Hub so it will still have the same problems I encountered.  Would be a good option if we did decide it was worth doing the work to make our approach work in Binder Hub.
